### ISSUE TITLE
Mobile Storefront - Refactor mobile-htmlhead-include

### ISSUE THREAD

**Issue by jj-lucas** [jackjonesfashion/tasks#117]
There's some messy inline styling on the mobile htmlhead include (we have an xml import for that)..
Please refactor it and plug it where most appropriate.

![image](https://cloud.githubusercontent.com/assets/2851890/7765745/d1f169b2-0061-11e5-85eb-edf862fdc396.png)

**Comment by jeppeolesen** [comment]
This is a duplicate of #85 

Closed
