### ISSUE TITLE
Storefront - increase line height of selling points

### ISSUE THREAD

**Issue by jj-lucas** [jackjonesfashion/tasks#123]
Make it look decent when text wraps on multiple lines.
Maybe obsolete with new frontpage.

![image](https://cloud.githubusercontent.com/assets/2851890/7930292/7819992e-0907-11e5-8e13-03c186ea297f.png)

**Comment by jeppeolesen** [comment]
Putting this in the updated storefront project. No need to work on this when the updated selling points are right around the corner.
