### ISSUE TITLE
Comp. module - Research possibilites

### ISSUE THREAD

**Issue by gitte-cort** [jackjonesfashion/tasks#126]
I would like to have a comp. module. DO IT!
![thum_73534d48d664008d5](https://cloud.githubusercontent.com/assets/12714294/7936158/45ac0154-0937-11e5-95b9-298ebe7a3207.jpg)

![image](https://cloud.githubusercontent.com/assets/12714294/7936160/4e905374-0937-11e5-8a23-692cb6193de9.png)

**Comment by jeppeolesen** [comment]
Yo!
