### ISSUE TITLE
PLP - category banner links in table format

### ISSUE THREAD

**Issue by katrine-olesen** [jackjonesfashion/tasks#127]
I would like to see if it would look nice with links in the category banners in a more uniform / table kind of look

Please do not spend a lot of time. I'm not sure we will go for the solution.

![image](https://cloud.githubusercontent.com/assets/7114538/7936580/720e9bc8-093a-11e5-99bd-f8bf01bc12f0.png)

**Comment by jeppeolesen** [comment]
cc @katrine-olesen 

I've made a quick test of what this would look like.

Please let me know if we should deploy this.

![image](https://cloud.githubusercontent.com/assets/1243023/8204124/82d393b6-14e6-11e5-992a-fc27d9d5db00.png)
