### ISSUE TITLE
SL - Possibility of hiding left hand navigation

### ISSUE THREAD

**Issue by katrine-olesen** [jackjonesfashion/tasks#128]
Selected has a top navigation
They have the the exact same in the left hand navigation.

Is it possible to hide this to make room for the filters in the left navigation?

![image](https://cloud.githubusercontent.com/assets/7114538/7937874/a550e1aa-0942-11e5-8140-99f24eddd3a3.png)

**Comment by jeppeolesen** [comment]
@katrine-olesen Some of the stuff can be hidden pretty easily. Have a look at the screenshot below.

Only a few of the elements ("Nyheder", "ALL", "Home" and "Blog") will be hard to hide, since they are built in a very generic way - Meaning if we hide them, we risk accidentally hiding other things on the site as well.

![image](https://cloud.githubusercontent.com/assets/1243023/7937955/230cac6e-0943-11e5-859d-4981a081f35b.png)

**Comment by jeppeolesen** [comment]
@katrine-olesen Looks like if we do what I just said, it will cause a bit of trouble for the subcategories. Check out the screenshot. It will hide everything except the currently active subcategory. We should have a talk about possible solutions, if this is something SL wishes to move on.

![image](https://cloud.githubusercontent.com/assets/1243023/7938934/8af578c4-0948-11e5-8f6d-bebaaf62d521.png)

**Comment by katrine-olesen** [comment]
Tak Jeppe - informationen er videregivet til Stine.
Det kan være de kontakter dig for yderligere hjælp.

Mvh.
Katrine

Den 02/06/2015 kl. 16.58 skrev Jeppe Hyldgaard Olesen <notifications@github.com<mailto:notifications@github.com>>:


@katrine-olesen<https://github.com/katrine-olesen> Looks like if we do what I just said, it will cause a bit of trouble for the subcategories. Check out the screenshot. It will hide everything except the currently active subcategory. We should have a talk about possible solutions, if this is something SL wishes to move on.

[image]<https://cloud.githubusercontent.com/assets/1243023/7938934/8af578c4-0948-11e5-8f6d-bebaaf62d521.png>

**Comment by jeppeolesen** [comment]
I had a talk with Stine and we'll be setting up the brand code for selected.com in that same way it's set up for jackjones.com

That will allow us to start doing this kind of work with them. Jimmy and Stine has okay'ed this, but we should probably let AMS know that it's happening.

**Comment by jeppeolesen** [comment]
- [ ] Transition SL to new code structure
- [ ] Hide left nav on categories

**Comment by jeppeolesen** [comment]
We're unable to chagne the Selected setup right now. On hold while we wait for E-com and Selected to make at decision on what to do going forward.

**Comment by jj-lucas** [comment]
Lucas Gabriel Salina D#Ovidio [03/06 - 13:54]: 
> make sure her managers approve that and back her up. It's gonna be a shitstorm if you have to roll back

#ROFL

**Comment by jeppeolesen** [comment]
Closing this, as it seems like a dead ticket for now.

This will either be addressed through "BING" or when E-com does an update to the custom objects.
