### ISSUE TITLE
Tech dashboard - Performance on iPad

### ISSUE THREAD

**Issue by jj-lucas** [jackjonesfashion/tasks#129]
On iPad mini, the navigation is painfully laggy.
Please investigate the cause / build a tablet friendly version

**Comment by jj-lucas** [comment]
Nevermind, the navigation lag seems not to occur anymore, probably it was cache.
Yesterday it made the page unusable.

**Comment by jeppeolesen** [comment]
Could be a multitude of stuff going on, but most likely it was either the ipad not having any free memory, or the server wasn't returning data quickly enough.

On 02/06/2015, at 19.23, jj-lucas <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #129<https://github.com/jackjonesfashion/tasks/issues/129>.
