### ISSUE TITLE
PLP - Filter for PIM tag

### ISSUE THREAD

**Issue by katrine-olesen** [jackjonesfashion/tasks#130]
Hi Jeppe 

We currently have a case open with e-commerce
It will not be fixed in the short run, if ever

Is the in any way something you can do to fix this?
As you can see on the picture, the text is on top of the check box.

<a href="https://bestseller.jira.com/browse/CDV-4658" target="_blank">CDV-4658</a>
DMW : Jack & Jones : Pim Tage filters

![image](https://cloud.githubusercontent.com/assets/7114538/7959318/65b5853a-09f8-11e5-8b9d-82c730e9f09c.png)

**Comment by katrine-olesen** [comment]
how it should look:

![image](https://cloud.githubusercontent.com/assets/7114538/7959340/a14b654c-09f8-11e5-837b-3d2a6cbdeea8.png)

**Comment by jeppeolesen** [comment]
Can you tell me where I can see this function? It's can't find it on the site, staging or our sandbox.

**Comment by katrine-olesen** [comment]
At the moment it is not turned on
Can you please ask trine to turn it on in a category.
She might have a hidden category already existing with the confinguration from last. 

Ask her to turn on a search refinment with PIM tag filters.

**Comment by katrine-olesen** [comment]
http://dws.jackjones.ch/shop/cuff/canvas/pants/jj-w16-cuff-canvas-pants-down,de_CH,sc.html
