### ISSUE TITLE
Font is not readable (all countries)

### ISSUE THREAD

**Issue by jj-marie** [jackjonesfashion/tasks#136]
Hej Jeppe!
I just saw that the font on how many products are available in a specific category is double layered and thus not readable (see screenshot for DE).
![capture](https://cloud.githubusercontent.com/assets/12825139/8076071/6992571e-0f48-11e5-9790-7c8060d7d540.JPG)

**Comment by jj-lucas** [comment]
https://bestseller.jira.com/browse/CDV-4545

**Comment by jeppeolesen** [comment]
While we wait for the CDV Lucas' mentioned to be fixed, I'll find some time and see if this is something we could fix ourselves, or if we're stuck waiting for Amsterdam.

**Comment by jeppeolesen** [comment]
Fixed.

Turns out the settings for the sub brands in Demandware were not properly done. It will go live tomorrow morning.
