### ISSUE TITLE
Wrong icons in SALE cat banner

### ISSUE THREAD

**Issue by katrine-olesen** [jackjonesfashion/tasks#141]
![image](https://cloud.githubusercontent.com/assets/7114538/8154051/70389e42-1336-11e5-89b5-ced360ec7643.png)

**Comment by katrine-olesen** [comment]
The hoover state is also not good

![image](https://cloud.githubusercontent.com/assets/7114538/8154085/cd9e56ee-1336-11e5-88dc-7f5c21d042a3.png)

**Comment by katrine-olesen** [comment]
@jj-lucas

**Comment by jj-lucas** [comment]
@jeppeolesen , apparently there's a sprite for icons after all:
http://demandware.edgesuite.net/aagb_prd/on/demandware.static/Sites-DK-Site/Sites/da_DK/v1434345099783/jack-jones/project-assets/catbanners/sale/assets/images/sprite-icons.png

The parser is already adding the "shorts" class, which was introduced in this deployment.

**Comment by jeppeolesen** [comment]
@Nikola-Nikolov is creating the icon we need for the category, and I'll be doing the coding later today.

@Kay3nta - Please keep in mind for the future, that any category we haven't run in the banner before will need to be coded in before launch.

**Comment by Nikola-Nikolov** [comment]
@jeppeolesen  Here is the image
![sprite-icons](https://cloud.githubusercontent.com/assets/7019780/8155605/2d505c86-1346-11e5-9ddf-43aaa1c1a2b5.png)

**Comment by jj-lucas** [comment]
@jeppeolesen She mentioned it, I just failed to inform you guys because i couldn't find image references in the markup / styling. Get over it, kiddos..

**Comment by Kay3nta** [comment]
We discussed that with Lucas, he was aware of this, and said its no problem

Doris Schoger
E-commerce   /   Campaign Responsible
P

+4599424286

M

+4552154286

E

doris.schoger@bestseller.com<mailto:doris.schoger@bestseller.com>

W

BESTSELLER.COM<http://bestseller.com>

BESTSELLER A/S
FREDSKOVVEJ 1, 7330 BRANDE
DENMARK
[cid:image001.png@01D0A75B.80A3B7E0]
