### ISSUE TITLE
Frontpage - Page is pink!

### ISSUE THREAD

**Issue by Mai-Mechlenborg** [jackjonesfashion/tasks#164]
Looks like something is wrong on the frontpage.

![lars](https://cloud.githubusercontent.com/assets/13198125/8519792/992b2a04-23d5-11e5-91eb-8de0e63e5fa3.png)
![image](https://cloud.githubusercontent.com/assets/13198125/8519797/9ec0bfec-23d5-11e5-869b-2fda4c3bb8e4.png)

**Comment by jeppeolesen** [comment]
Hello!
