### ISSUE TITLE
PLP: Update styling to support "in-paragraph" anchors

### ISSUE THREAD

**Issue by jj-lucas** [jackjonesfashion/tasks#168]
We're about to start deploying anchors in the text catbanners paragraphs.
Please update it so it doesn't fuck up.
A simple underline will do.

![image](https://cloud.githubusercontent.com/assets/2851890/8647072/11708660-2955-11e5-954d-0957aa089f06.png)

**Comment by jj-lucas** [comment]
@jj-marie

**Comment by jj-marie** [comment]
Or make it appear bold instead of underlining so people get it's clickable (instead of underlining), maybe more visually attractive  @jeppeolesen

**Comment by jj-lucas** [comment]
![image](https://cloud.githubusercontent.com/assets/2851890/8647378/c6e78500-2957-11e5-9fbb-435960737ea5.png)

**Comment by jeppeolesen** [comment]
@jj-lucas @jj-marie Let me know when you've deployed something - and where I can see it - and I'll fix it today

**Comment by jj-lucas** [comment]
We won't deploy until the styling is ok.. Just add an anchor via the inspector, it takes 2 seconds ;)

**Comment by jeppeolesen** [comment]
I've deployed the updated styling. It will look the same as the SEO banner to keep the UX consistant across the elements. It will be replicated tomorrow morning.

**Comment by jj-lucas** [comment]
have link position always been left aligned by default? Or is it a result of this fix?

![image](https://cloud.githubusercontent.com/assets/2851890/8668219/037ec6ac-2a09-11e5-9c00-1718b0a07b71.png)

Any chance to make it centered horizontally?

Here a test link for the fix above: http://dws.jackjones.de/on/demandware.store/Sites-DE-Site/de_DE/Search-InternalUrl?cgid=jj-j-shop-knit&productsperrow=3&forcecountry=DE&forcebrand=jack-jones

**Comment by jeppeolesen** [comment]
@jj-lucas Links are centered. It's because the text is so short, that it doesn't fill out the width of the container and the links appear to  be left aligned.

**Comment by jj-lucas** [comment]
![image](https://cloud.githubusercontent.com/assets/2851890/8668564/bfd4934c-2a0c-11e5-8a86-e9d8379f537c.png)

**Comment by jeppeolesen** [comment]
@jj-lucas Nope. Or well, if you wanna change the markup of the template you deploy to work in rows we could do something like this. Otherwise we should try to have a least 3 links in the banner.

**Comment by jj-lucas** [comment]
@jj-marie Wherever possible, please ensure that categories have at least 3 links, to look visually nice
