### ISSUE TITLE
No results page - Change link of jeans spot

### ISSUE THREAD

**Issue by Doris-Schoger** [jackjonesfashion/tasks#180]
Change the link on the jeans spot to point at the jeans category.

-----
**Category to point to: jj-j-shop-jeans**
**Live-date: 14/8**

**Comment by jeppeolesen** [comment]
@Doris-Schoger Is this the category you want it to point to?

http://jackjones.dk/shop/jeans/jj-j-shop-jeans,da_DK,sc.html?productsperrow=3

**Comment by Doris-Schoger** [comment]
yes

Doris Schoger
E-commerce   /   Campaign Responsible
P

+4599424286

M

+4552154286

E

doris.schoger@bestseller.com<mailto:doris.schoger@bestseller.com>

W

BESTSELLER.COM<http://bestseller.com>

BESTSELLER A/S
FREDSKOVVEJ 1, 7330 BRANDE
DENMARK
[cid:image001.png@01D0CAC2.536F65A0]

**Comment by jj-lucas** [comment]
@jeppeolesen You are coming back on the 13th, for the meeting. Is this task taken care of? Want me to look into it?

**Comment by jj-lucas** [comment]
@Doris-Schoger Consider updating the copy of the spot
![image](https://cloud.githubusercontent.com/assets/2851890/9269739/aaf3a954-426c-11e5-8e6f-b812abff25bc.png)

**Comment by Doris-Schoger** [comment]
It should be updated and changed.

Where do you want to put it in?

**Comment by jj-lucas** [comment]
i just updated the link of htat spot, but i think the wording "jeans guide" is a bit irrelevant, as we point to the entire jeans category
