### ISSUE TITLE
Storefront - Promo Boxes

### ISSUE THREAD

**Issue by jeppeolesen** [jackjonesfashion/tasks#188]

**Comment by jeppeolesen** [comment]
Currently on hold, waiting for E-com to deploy the new template.

**Comment by jj-lucas** [comment]
Add a bit of specs on the scope of the change.
Usual drill: What, how, how often, who, all you know..
Tiptoe around the why.

**Comment by jeppeolesen** [comment]
@jj-lucas We're gonna have a meeting about that tomorrow when you're back.

For now:
*What:*
* Min 2 - Max 8 promoboxes introduced below the hero
* Boxes contain one image, CTA, description and link.

*How:*
* Content slots, same as always. Template updated to support it.

*How often:*
* Once a week, following brand-sites and WR schedule

*Who:*
* Products and Focus: Jesper F + Brands
* Copy: Karina
* Images: Graphics

*Why:*
* Because MM said so

**Comment by jeppeolesen** [comment]
![](http://www.reactiongifs.com/r/wtthll.gif)

**Comment by jj-lucas** [comment]
That gif is perfect. I'm out for 4 days, and this happens :D

**Comment by jeppeolesen** [comment]
Left to do: Update styling and deploy content

**Comment by jeppeolesen** [comment]
... oh, and also building a tool. https://github.com/jackjonesfashion/wiz/issues/392

**Comment by jeppeolesen** [comment]
*Deployment status*

Create content on SE market:

X | DE | DK | ES | FI | FR | NL | NO | SE |
---------------------------------------------------
