### ISSUE TITLE
Subbrand, Jeans - Remove content and hero overlay

### ISSUE THREAD

**Issue by Nikola-Nikolov** [jackjonesfashion/tasks#189]
Hey Jeppe

as we spoke please add space between the hero on the jeans page and the 3 boxes. 
![cunr8](https://cloud.githubusercontent.com/assets/7019780/9441410/35838222-4a76-11e5-94a3-192963e3da24.gif)

**Comment by jeppeolesen** [comment]
![](http://www.reactiongifs.com/r/yfu.gif)

**Comment by Nikola-Nikolov** [comment]
![images](https://cloud.githubusercontent.com/assets/7019780/9441952/27ba1f68-4a79-11e5-8b66-39b8562f103a.png)

**Comment by jeppeolesen** [comment]
![](http://www.reactiongifs.com/r/tmimn.gif)
