### ISSUE TITLE
Misc. pages - Terms & Conditions, Denim Heroes

### ISSUE THREAD

**Issue by jj-lucas** [jackjonesfashion/tasks#47]
Anna Sarah will deliver simple mockup + pics + reviewed EN text. Not nationalized. 
To be live around the 20th feb,

~~http://jackjones.de/Terms-and-conditions/jj-sustainability-terms-and-conditions,de_DE,pg.html~~

**Comment by jeppeolesen** [comment]
@jj-lucas Where's the design for this?

**Comment by jeppeolesen** [comment]
This is a new T&C page.

@jj-lucas - For future reference, be very clear about the fact that it's a new piece of content. If that hadn't slipped into the conversation I would have updated the sustainability T&Cs, since that was the link you put in the description.

**Comment by jj-lucas** [comment]
![](http://www.reactiongifs.com/r/gtm.gif)

**Comment by jeppeolesen** [comment]
@jj-lucas - Uhm.. What? Are you that excited about a Terms & Conditions page?
