### ISSUE TITLE
Category Banner, Video - Dani/Marc

### ISSUE THREAD

**Issue by jeppeolesen** [jackjonesfashion/tasks#59]
Live: ~~23/3~~ Campaign postponed, new dates will be communicated by Doris.

Redeployment and update of the old video category banner

**Comment by jj-lucas** [comment]
Coming up on the 26/4.
Expecting a Campaign brief with intel (vimeo ID of uploaded vid in custom worksheet)

**Comment by jj-lucas** [comment]
Jeppe Hyldgaard Olesen	When you finish the Dani marc banner thing, please close the ticket and the milestone for april
	13:36
	https://github.com/jackjonesfashion/tasks/milestones

**Comment by jj-lucas** [comment]
Done, i guess?

**Comment by jeppeolesen** [comment]
![](http://www.reactiongifs.com/r/hiii.gif)
