### ISSUE TITLE
In project repos, add installation instructions to readme

### ISSUE THREAD

**Issue by jj-lucas** [jackjonesfashion/tasks#6]
guess what, styling changes in the Sales catbanner. Looking at it it would seem that it's a gulp project, but gulp build only builds images and fonts. I guess this is to be run via Prepos.
Add a line of comment as to what's to do to update the project, in the future

**Comment by jeppeolesen** [comment]
@jj-lucas I don't really get what you want me to update here? The readme is maintained within the "Project-template". I'm not going to maintain a readme across multiple repos.
