### ISSUE TITLE
Brandsites: Issue with navigating back after viewing a video

### ISSUE THREAD

**Issue by jj-lucas** [jackjonesfashion/tasks#80]
http://jackjones.dk/lifestyles/vintage/jj-vintage,da_DK,sc.html

open the video
close the video
navigate backwards with the browser

this is the result:
![image](https://cloud.githubusercontent.com/assets/2851890/7018271/8a573618-dd02-11e4-995e-46029e30c983.png)

**Comment by jeppeolesen** [comment]
Tried different approaches - Problem here is that iframes actively manipulate the window.history object when triggered, and the entry can't be removed from the history by javascript

Alternative ideas:
- oembed (Old tech, but might work)
- Customized html5 video module (No iframe = no entry to window.history)
- Dynamically injecting the iframe markup (Might give issues with the Vimeo api and event bindings)

**Comment by jeppeolesen** [comment]
Oembed was the way to go.
