### ISSUE TITLE
PLP: Move product badge according to Onurs mail

### ISSUE THREAD

**Issue by ahmikkelsen** [jackjonesfashion/tasks#86]
Size, position etc. has to be changed for it to work :)

See Onurs mail from the 10th

![image](https://cloud.githubusercontent.com/assets/6907325/7086716/6ea6646e-df84-11e4-8c03-4497e9ad1bbf.png)

**Comment by jeppeolesen** [comment]
@ahmikkelsen - Position of the badges has been updated. Please coordinate with Katrine or Trine about uploading the image assets and activating the badges.
